---
blank_issues_enabled: false
contact_links:
  - about: "Ask and answer usage questions on Stack Overflow."
    name: Question
    url: "https://stackoverflow.com/questions/tagged/node-package-template"
  - about: "Check the FAQ before filing new issues."
    name: "FAQ"
    url: "https://github.com/harrysolovay/node-package-template/README.md#faq"
