name: Test
on:
  pull_request:
    branches: "*"
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
        node-version: [10.x, 12.x, 13.x, 14.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - run: npm ci
      - run: yarn check
      - run: yarn test
